import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";
import { AuthContextProvider } from "@/context/auth_context";
import { Provider } from "jotai";
import SessionProvider from "./SessionProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthContextProvider>
          <SessionProvider>
            <Provider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Header />
                {children}
                {/* Footer */}
                <footer className="border-t-2 bg-primary p-4 text-foreground">
                  <p>&copy; 2024 Telepresence Robot App</p>
                  {/* Add any additional footer content */}
                </footer>
              </ThemeProvider>
            </Provider>
          </SessionProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
